"""Internal CLI (operator-only, never shipped to customers): signs a
license token with the private half of the keypair generated by
infra/scripts/gen-license-keypair.sh. Not run inside any customer's
deployment - this produces the LICENSE_TOKEN value that goes into their
.env.

    python -m apps.api.scripts.generate_license "Acme Inc" \\
        --seats 25 --days 365 --modules policy,tools,escalations,training
"""
import argparse
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import jwt

REPO_ROOT = Path(__file__).resolve().parents[3]
PRIVATE_KEY_PATH = REPO_ROOT / "secrets" / "license_signing_key.pem"


def generate_license(org_name: str, seat_count: int, days: int, enabled_modules: list[str]) -> str:
    if not PRIVATE_KEY_PATH.exists():
        print(f"Private key not found at {PRIVATE_KEY_PATH}. Run infra/scripts/gen-license-keypair.sh first.", file=sys.stderr)
        sys.exit(1)

    private_key = PRIVATE_KEY_PATH.read_text()
    now = datetime.now(timezone.utc)
    payload = {
        "org_name": org_name,
        "seat_count": seat_count,
        "issued_at": now.isoformat(),
        "expires_at": (now + timedelta(days=days)).isoformat(),
        "enabled_modules": enabled_modules,
    }
    return jwt.encode(payload, private_key, algorithm="RS256")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a signed Project Misty license token")
    parser.add_argument("org_name")
    parser.add_argument("--seats", type=int, default=10)
    parser.add_argument("--days", type=int, default=365)
    parser.add_argument("--modules", default="policy,tools,escalations,training")
    args = parser.parse_args()

    token = generate_license(args.org_name, args.seats, args.days, args.modules.split(","))
    print(token)
